#!/usr/bin/env python3
"""Writes src/n3ds/n3ds_gate_vtable.inc: a wrapper for each RendererVtable entry (src/renderer.h) that opens the GPU frame
(N3DSRenderer_frameGate) before calling the 3DS renderer's own entry. Pure queries go straight through.

The 3DS main loop runs the game step while the GPU still draws the previous frame; citro3d's command and vertex
buffers belong to that frame until C3D_FrameBegin has waited for it, so the first renderer call that may touch the
GPU (a draw, a surface or state change from a Step event) opens the frame. Run again when RendererVtable changes:
    python3 tools/n3ds/gen_gate_vtable.py
"""
import os, re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
# Entries that only read renderer state (or run outside the main loop): no frame needed.
UNGATED = {
    "init", "destroy", "gpuGetBlendFactors", "gpuGetBlendMode", "gpuGetAlphaTestEnable", "gpuGetColorWriteEnable",
    "gpuGetBlendEnable", "getVisibleRoomRect", "surfaceExists", "getSurfaceWidth", "getSurfaceHeight",
    "shaderGetUniform", "shaderGetSamplerIndex", "shaderIsCompiled", "shadersSupported", "textureGetTexelWidth",
    "textureGetTexelHeight",
}

src = open(os.path.join(ROOT, "src", "renderer.h")).read()
start = src.index("typedef struct {\n    void (*init)(Renderer* renderer, DataWin* dataWin);")
body = src[start:src.index("} RendererVtable;", start)]
body = re.sub(r"//[^\n]*", "", body)
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
entries = re.findall(r"([A-Za-z_][\w\s\*]*?)\(\s*\*\s*(\w+)\s*\)\s*\(([^)]*)\)\s*;", body.split("{", 1)[1])

out = ["// Generated by tools/n3ds/gen_gate_vtable.py from src/renderer.h: do not edit.", "",
       "static const RendererVtable* gGateReal;", ""]
installs = []
for ret, name, params in entries:
    ret = " ".join(ret.split())
    if name in UNGATED:
        continue
    plist = [p.strip() for p in params.split(",") if p.strip() and p.strip() != "void"]
    names = [re.findall(r"(\w+)\s*$", p)[0] for p in plist]
    call = "gGateReal->%s(%s)" % (name, ", ".join(names))
    out.append("static %s N3DSGate_%s(%s) {" % (ret, name, ", ".join(plist) or "void"))
    out.append("    N3DSRenderer_frameGate();")
    out.append("    %s%s;" % ("" if ret == "void" else "return ", call))
    out.append("}")
    installs.append("    if (real->%s != NULL) gate->%s = N3DSGate_%s;" % (name, name, name))
out += ["", "// gate: a copy of real with the GPU-touching entries replaced by the wrappers above.",
        "static void N3DSGate_install(RendererVtable* gate, const RendererVtable* real) {",
        "    *gate = *real;", "    gGateReal = real;"] + installs + ["}", ""]
open(os.path.join(ROOT, "src", "n3ds", "n3ds_gate_vtable.inc"), "w").write("\n".join(out))
print("%d entries, %d gated" % (len(entries), len(installs)))
